### PR TITLE
Switch to -Z build-std

### PR DESCRIPTION
**Pull request by sameo**
It is now a standard cargo feature.

### CODE REVIEW

**Comment by sameo** [comment]
cc @jyao1

**Review by xiaoyuxlu — APPROVED** [review]
It’s great to be able to use cargo’s own feature.
And thanks for correcting a lot of format issues.

**Comment by jyao1** [comment]
@sameo, sorry, I missed that.

Do you observe any size different between those two options?

Per our experience, we see different result.

I have no concern, if the result is identical.

**Comment by xiaoyuxlu** [comment]
x86_64-unknown-uefi/release/libspdmlib.rlib
cargo xbuild size: 5112850
-Z build-std size: 5112736

**Pull request merged**
