### PR TITLE
add slot_id check

### PR DESCRIPTION
**Pull request by xiaotia3**
fix typo.
slot_id must less than SPDM_MAX_SLOT_NUMBER.

Fix: https://github.com/jyao1/rust-spdm/issues/497

### CODE REVIEW

**Comment by jyao1** [comment]
good catch!

**Comment by jyao1** [comment]
There are totally 4 places having similar issue - `if slot_id > SPDM_MAX_SLOT_NUMBER {`

Are you planning to fix all of them?

**Comment by xiaotia3** [comment]
Sure

**Comment by jyao1** [comment]
NOTE: Slot ID could be 0xF or 0xFF in case of PUB_KEY_ID feature. But that is not supported yet (https://github.com/jyao1/rust-spdm/issues/530).

So current patch is good enough.

**Pull request merged**
